# .goreleaser.yml
# Build customization
builds:
  # makefile currently relies on this name
  - binary: mobile-client-service
    main: ./cmd/api-server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  