# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[override]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "v0.1.18"

[[constraint]]
  name = "github.com/openshift/client-go"
  version = "v3.9.0"

[[constraint]]
  name = "github.com/openshift/api"
  version = "v3.9.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.20.2"
