apiVersion: v1
kind: Template
metadata:
  name: mobile-client-service-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          app: "${SERVICE_NAME}"
      spec:
        containers:
        - name: "${SERVICE_NAME}"
          image: ${SERVER_IMAGE}
          ports:
          - containerPort: ${SERVER_PORT}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    ports:
    - name: "${SERVER_PORT}-tcp"
      port: "${SERVER_PORT}"
      protocol: TCP
    selector:
      app: "${SERVICE_NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    port:
      targetPort: "${SERVER_PORT}-tcp"
    tls:
      termination: edge
    to:
      kind: Service
      name: "${SERVICE_NAME}"
parameters:
- name: SERVER_PORT
  description: The port for the server to listen on.
  value: "4000"
  required: true
- name: SERVER_IMAGE
  description: The image to create the server from.
  value: aerogear/mobile-client-service:latest
  required: true
- name: SERVICE_NAME
  description: What to name the service/application in OpenShift. Selectors will be updated also.
  value: mobile-client-service
  required: true
