apiVersion: v1
kind: Template
metadata:
  name: mobile-developer-console-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          app: "${SERVICE_NAME}"
      spec:
        securityContext: {}
        serviceAccount: "${SERVICE_ACCOUNT_NAME}"
        serviceAccountName: "${SERVICE_ACCOUNT_NAME}"
        containers:
        - name: "${SERVICE_NAME}"
          image: ${SERVER_IMAGE}
          ports:
          - containerPort: ${SERVER_PORT}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    ports:
    - name: "${SERVER_PORT}-tcp"
      port: "${SERVER_PORT}"
      protocol: TCP
    selector:
      app: "${SERVICE_NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: "${SERVICE_NAME}"
    name: "${SERVICE_NAME}"
  spec:
    port:
      targetPort: "${SERVER_PORT}-tcp"
    tls:
      termination: edge
    to:
      kind: Service
      name: "${SERVICE_NAME}"

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: "${SERVICE_ACCOUNT_NAME}"

parameters:
- name: SERVER_PORT
  description: The port for the server to listen on.
  value: "4000"
  required: true
- name: SERVER_IMAGE
  description: The image to create the server from.
  value: aerogear/mobile-developer-console:latest
  required: true
- name: SERVICE_NAME
  description: What to name the service/application in OpenShift. Selectors will be updated also.
  value: mobile-developer-console
  required: true
- name: SERVICE_ACCOUNT_NAME
  description: What to name the service account to run this service
  value: mobile-developer-console
  required: true
